apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: my-azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-azurefile
  csi:
    driver: file.csi.azure.com
    volumeHandle: "MC_contoso-aks-go-eastus2-RG_aks-demo-jkydnjvbl72wg-cluster_eastus2#f3244aaa9e97f4e30aac204#my-azurefile-pv###default"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: aksshare
    nodeStageSecretRef:
      name: azure-storage-account-f3244aaa9e97f4e30aac204-secret
      namespace: default
  claimRef:
    namespace: default
    name: my-azurefile
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks