apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-dynamic-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi