apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-static-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile-static-pv
  resources:
    requests:
      storage: 1024Gi