apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  volumeName: my-azurefile-pv    
  resources:
    requests:
      storage: 100Gi