apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-azurefile-csi-storageclass
  annotations:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict